### ISSUE TITLE
Logging out and logging in crashes app

### ISSUE THREAD

**Issue by BOBODDY** [BOBODDY/SYNC-app#1]
After successfully logging into the app, logout and then try to log back in again and the app crashes

```
06-29 13:20:14.620    7770-7770/com.sync.syncapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.sync.syncapp, PID: 7770
    java.lang.IllegalStateException: Activity has been destroyed
            at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1350)
            at android.app.BackStackRecord.commitInternal(BackStackRecord.java:728)
            at android.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:708)
            at com.sync.syncapp.activities.MainActivity.selectItem(MainActivity.java:222)
            at com.sync.syncapp.activities.MainActivity.access$000(MainActivity.java:41)
            at com.sync.syncapp.activities.MainActivity$1.onReceive(MainActivity.java:67)
            at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
            at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
            at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by BOBODDY** [comment]
This seems fixed. Not sure how...
